services:
  - type: web
    name: engineering-college-platform
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_ENV
        value: production

      - key: SECRET_KEY
        sync: false

      - key: DATABASE_URL
        sync: false